feat:added presentation exchange flow integration test
hyperledger/aries-acapy-plugin-toolbox pull request #110
Opened 2021-10-29 20:44 UTC by PeterStrob

Signed-off-by: PeterStrob <peter@indicio.tech>

2021-10-29 21:20 UTC, cjhowland approved these changes
Looks great to me!

2021-10-29 22:07 UTC, dbluhm commented
We'll have to fix up tests before merging but I second Char, additions look good :slightly_smiling_face:

2021-10-29 22:36 UTC, frostyfrog commented on acapy_plugin_toolbox/holder/v0_1/messages/pres_request_received.py
> +        self.presentation_request = record.presentation_request.serialize()
With the work day nearly over here, I just wanted to mention that this change is what's causing the other tests to fail. For whatever reason, some of the other tests are not setting the `presentation_request` attribute on the `PresExRecord` object, causing the `.serialize()` to fail against the `NoneType` Object Type.

2021-11-04 13:39 UTC, dbluhm requested changes
A few last minor comments. Nice work!

2021-11-04 13:39 UTC, dbluhm commented on int/tests/test_presentation_integration.py
> +from acapy_client.models.indy_proof_request import IndyProofRequest
I think I'd rename this file to `test_presentation` since it's already in the integration test folder.

2021-11-04 13:39 UTC, dbluhm commented on tests/holder/test_events.py
> +
Was this addition necessary? I don't see `typing` used anywhere in the other additions to this test.

2021-11-04 13:39 UTC, dbluhm commented on tests/holder/test_events.py
> +    )
Is this change necessary for the presentation integration test?

2021-11-05 14:16 UTC, dbluhm commented on int/tests/test_presentation_integration.py
> +from acapy_client.models.indy_proof_request import IndyProofRequest
We now have a duplicate file :grimacing:

2021-11-05 14:43 UTC, dbluhm approved these changes

2021-11-05 14:43 UTC, merged